services:
  company-dashboard:
    build:
      context: .
      target: prod
    image: shfayetwt/time-tracking-company-dashboard:latest
    container_name: company-dashboard
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
